### ISSUE TITLE
Post-hoc differential gene expression analysis

### ISSUE THREAD

**Issue by MikeDMorgan** [MarioniLab/milo#13]
More for the paper than the package - but can we identify genes that differ by the same experimental variable as for the DA testing in just the DA neighbourhoods. Are there any caveats to these, e.g. potentially overlapping cells between neighbourhoods with opposite sign effects?

We should have some methods to facilitate this, i.e. extract gene expression from the DA neighbourhoods, etc.

**Comment by MikeDMorgan** [comment]
Functions for performing DGE analysis now incorporated into the `miloR` repo.

**Comment by emdann** [comment]
From the code I understand that the function tests for differences between conditions A and B _within_ a group of nhoods i.e. all the nhoods that have logFC up. But shouldn't the test compare the group with logFC up and logFC down? (At least this is what I was doing on this front)

Say I have a cell type cluster where I find DA. Here I'll have one group of logFC+ and one group of logFC- nhoods. I am interested in finding what's different between those groups, not the difference between A and B in the logFC+ (also because cells in the same nhood group are very close in the knn graph, hence for single cell standard they are the same population, hence I expect no difference)

**Comment by MikeDMorgan** [comment]
You want `findNhoodMarkers` to identify genes _between_ neighbourhoods. `testDiffExp` is the _within_ aggregated neighbourhood function.

**Comment by emdann** [comment]
Whoopsie nevermind

**Comment by MikeDMorgan** [comment]
No worries ;)
